name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - br_2306_f1_cardlayoutweb
  pull_request:
    branches: 
      - br_2306_f1_cardlayoutweb

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/narayanpunekar/cardlayoutweb
            azure-pipeline-name: 'cardlayoutwebBuild-Maven with SonarCloud-CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
